# Generated by Django 5.1.6 on 2025-02-16 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('icon', models.ImageField(upload_to='media/category_icons/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/Seller_image')),
                ('backgroud_image', models.ImageField(blank=True, null=True, upload_to='media/Seller_backgroud_image')),
                ('sold', models.IntegerField(blank=True, null=True)),
                ('income', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pages', models.IntegerField()),
                ('file_size', models.FloatField(help_text='File size in MB')),
                ('file_type', models.CharField(choices=[('pptx', 'Pptx'), ('pdf', 'Pdf'), ('docx', 'Docx')], max_length=10)),
                ('file', models.FileField(upload_to='media/products/')),
                ('poster', models.ImageField(upload_to='media/product_poster')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='app.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.seller')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
