# Generated by Django 5.1.6 on 2025-02-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='backgroud_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/Seller_backgroud_image'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/Seller_image'),
        ),
    ]
